let products = [
  {
    id: 1,
    video: "vedio/5403171432_4_2_1.mp4",
  },
  {
    id: 2,
    title: "colour block skater jeans",
    price: "1600",
    Image: "image/janes/colour-block-skater-jeans.webp",
    qtr: 1,
  },
  {
    id: 3,
    title: "Loose knit pants",
    price: "1700",
    Image: "image/janes/Loose-knit-pants.webp",
    qtr: 1,
  },
  {
    id: 4,
    title: "Mega baggy jeans",
    price: "1800",
    Image: "image/janes/mega-baggy-jeanswebp.webp",
    qtr: 1,
  },
  {
    id: 5,
    title: "Skater jeans",
    price: "1400",
    Image: "image/janes/skater-jeans.webp",
    qtr: 1,
  },
  {
    id: 6,
    title: "Skater Jeans black",
    price: "1200",
    Image: "image/janes/skater-jeans-blackwebp.webp",
    qtr: 1,
  },

  {
    id: 7,
    title: "Skater jogger jeans",
    price: "1900",
    Image: "image/janes/skater-jogger-jeans.webp",
    qtr: 1,
  },
  {
    id: 8,
    title: "Ski cut trousers pants",
    price: "1100",
    Image: "image/janes/Ski-cut-trousers-pants.webp",
    qtr: 1,
  },
  {
    id: 9,
    title: "Slim fit black jeans",
    price: "2000",
    Image: "image/janes/slim-fit-black-jeans.webp",
    qtr: 1,
  },
  {
    id: 10,
    title: "Slim fit blue jeans",
    price: "1700",
    Image: "image/janes/slim-fit-blue-jeans.webp",
    qtr: 1,
  },
  {
    id: 11,
    title: "Slim-fit-jeans",
    price: "1100",
    Image: "image/janes/slim-fit-jeans.webp",
    qtr: 1,
  },
  {
    id: 12,
    title: "Straight fit jeans",
    price: "1150",
    Image: "image/janes/Straight-fit-jeans.webp",
    qtr: 1,
  },
  {
    id: 13,
    title: "Super baggy",
    price: "1250",
    Image: "image/janes/super-baggy.webp",
    qtr: 1,
  },
  {
    id: 14,
    title: "Super baggy black jeans",
    price: "1450",
    Image: "image/janes/super-baggy-black-jeans.webp",
    qtr: 1,
  },
  {
    id: 15,
    title: "Super baggy jeans",
    price: "1850",
    Image: "image/janes/super-baggy-jeans.webp",
    qtr: 1,
  },
  {
    id: 16,
    title: "Wide formal trousers",
    price: "1550",
    Image: "image/janes/Wide-formal-trousers.webp",
    qtr: 1,
  },
  {
    id: 17,
    title: "wide sweetpantswebp",
    price: "2500",
    Image: "image/janes/wide-sweetpantswebp.webp",
    qtr: 1,
  },
  {
    id: 18,
    video: "vedio/sweetpants.mp4",
  },
  {
    id: 19,
    title: "Anckle boot",
    price: "5500",
    Image: "image/shoes/anckle-boot.webp",
    qtr: 1,
  },
  {
    id: 20,
    title: "Mens denim sneakers",
    price: "1900",
    Image: "image/shoes/mens-denim-sneakers.webp",
    qtr: 1,
  },
  {
    id: 21,
    title: "Mens denim sneakers",
    price: "1300",
    Image: "image/shoes/men-sneaker.webp",
    qtr: 1,
  },
  {
    id: 22,
    title: "Sport shoes",
    price: "1700",
    Image: "image/shoes/sport-shoes.webp",
    qtr: 1,
  },

  {
    id: 23,
    title: "white sport shoes",
    price: "950",
    Image: "image/shoes/white-sport-shoes.webp",
    qtr: 1,
  },
  {
    id: 24,
     video: "vedio/shorts.mp4",
  },
  {
    id: 25,
    title: "Bermuda shorts whith wide leg",
    price: "2050",
    Image: "image/shorts/bermuda-shorts-whith-wide-leg.webp",
    qtr: 1,
  },
  {
    id: 26,
    title: "Soft Bermuda shorts",
    price: "2100",
    Image: "image/shorts/Soft-Bermuda-shorts.webp",
    qtr: 1,
  },
  {
    id: 27,
    title: "Soft white bermuda",
    price: "2150",
    Image: "image/shorts/soft-white-bermuda.webp",
    qtr: 1,
  },
  {
    id: 28,
    title: "Sporty green bermuda",
    price: "2150",
    Image: "image/shorts/sporty-green-bermuda.webp",
    qtr: 1,
  },

  {
    id: 30,
    title: "Boxy fit T-shirt",
    price: "950",
    Image: "image/t-shirt/boxy-fit-T-shirt.webp",
    qtr: 1,
  },
  {
    id: 31,
    title: "Squre cut babyblue T-shirt",
    price: "1300",
    Image: "image/t-shirt/squre-cut-babyblue-T-shirt.webp",
    qtr: 1,
  },
  {
    id: 32,
    title: "Squre cut green T-shirt",
    price: "1000",
    Image: "image/t-shirt/squre-cut-green-T-shirt.webp",
    qtr: 1,
  },
  {
    id: 33,
    title: "Squre cut-whit print",
    price: "1600",
    Image: "image/t-shirt/squre-cut-whit-print.webp",
    qtr: 1,
  },
  {
    id: 34,
    title: "T-shirt 96",
    price: "1100",
    Image: "image/t-shirt/T-shirt-96.webp",
    qtr: 1,
  },
];

// ******************************************************
localStorage.setItem("products", JSON.stringify(products));

